h2o.num_iterations(glm_fit)
h2o.null_dof(glm_fit, train = TRUE, valid = TRUE)
h2o.residual_dof(glm_fit, train = TRUE, valid = TRUE)

h2o.mse(glm_fit, train = TRUE, valid = TRUE)
h2o.r2(glm_fit, train = TRUE, valid = TRUE)
h2o.logloss(glm_fit, train = TRUE, valid = TRUE)
h2o.auc(glm_fit, train = TRUE, valid = TRUE)
h2o.giniCoef(glm_fit, train = TRUE, valid = TRUE)
h2o.null_deviance(glm_fit, train = TRUE, valid = TRUE)
h2o.residual_deviance(glm_fit, train = TRUE, valid = TRUE)
h2o.aic(glm_fit, train = TRUE, valid = TRUE)
